// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1AhBVx56kVpF1L1RY9udkot0w6td7cts',
    appId: '1:21788102904:web:089ba7cbdb5356967aeb0d',
    messagingSenderId: '21788102904',
    projectId: 'raxxy-6ffec',
    authDomain: 'raxxy-6ffec.firebaseapp.com',
    storageBucket: 'raxxy-6ffec.firebasestorage.app',
    measurementId: 'G-HM2S35BWPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsZzty2zMyTjRPekT1sUaHs1-ww_Ib0lg',
    appId: '1:21788102904:android:3327d6d94c8208697aeb0d',
    messagingSenderId: '21788102904',
    projectId: 'raxxy-6ffec',
    storageBucket: 'raxxy-6ffec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF9qW8yzz07nz9_piJlSfN8goFY5vIryM',
    appId: '1:21788102904:ios:492d8ef14c7530b47aeb0d',
    messagingSenderId: '21788102904',
    projectId: 'raxxy-6ffec',
    storageBucket: 'raxxy-6ffec.firebasestorage.app',
    iosBundleId: 'com.example.raxxy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF9qW8yzz07nz9_piJlSfN8goFY5vIryM',
    appId: '1:21788102904:ios:492d8ef14c7530b47aeb0d',
    messagingSenderId: '21788102904',
    projectId: 'raxxy-6ffec',
    storageBucket: 'raxxy-6ffec.firebasestorage.app',
    iosBundleId: 'com.example.raxxy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1AhBVx56kVpF1L1RY9udkot0w6td7cts',
    appId: '1:21788102904:web:745ddb18fd35787c7aeb0d',
    messagingSenderId: '21788102904',
    projectId: 'raxxy-6ffec',
    authDomain: 'raxxy-6ffec.firebaseapp.com',
    storageBucket: 'raxxy-6ffec.firebasestorage.app',
    measurementId: 'G-ES6C409PB3',
  );

}